version: "3"
services:
  app:
    build: .
    image: ghcr.io/yude/telnetter
    volumes:
      - type: bind
        source: ./content
        target: /app/content
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 23:2000
