version: "3"
services:
  app:
    build: .
    image: ghcr.io/yude/telnetter
    volumes:
      - type: bind
        source: ./message.txt
        target: /app/message.txt
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 23:2000
